# Generated by Django 5.0.4 on 2024-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frase',
            name='ds_frase_idioma_2_observacao',
            field=models.CharField(max_length=50, null=True, verbose_name='Frase idioma aprendizado'),
        ),
    ]
