# Generated by Django 5.0.4 on 2024-05-04 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_escolaridade', models.CharField(max_length=30, unique=True)),
                ('ds_escolaridade', models.CharField(max_length=100, null=True)),
                ('vl_escolaridade', models.IntegerField(default=0, null=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_inclusao', models.IntegerField(default=0)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True)),
                ('dt_exclusao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_idioma', models.CharField(max_length=30, unique=True)),
                ('ds_idioma', models.CharField(max_length=50, null=True)),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True)),
                ('nm_arquivo_estilo_css', models.CharField(max_length=50, null=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_inclusao', models.IntegerField(default=0)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True)),
                ('dt_exclusao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_jogador', models.CharField(max_length=80)),
                ('nm_avatar', models.CharField(max_length=20, unique=True)),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True)),
                ('dt_nascimento', models.DateField()),
                ('tipo_genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não informado')], max_length=1)),
                ('cd_cep', models.CharField(max_length=8, null=True)),
                ('nm_email', models.EmailField(max_length=50, unique=True)),
                ('_nm_senha', models.CharField(db_column='nm_senha', max_length=20)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_inclusao', models.IntegerField(default=0)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True)),
                ('dt_exclusao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True)),
                ('id_idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogadores.idioma')),
                ('tp_escolaridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogadores.escolaridade')),
            ],
        ),
    ]
