# Generated by Django 5.0.4 on 2024-05-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='tipo_genero',
            new_name='tp_genero',
        ),
        migrations.RemoveField(
            model_name='escolaridade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='tp_escolaridade',
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='id_escolaridade',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='idioma',
            name='id_idioma',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='jogador',
            name='id_escolaridade',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.escolaridade'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='id_jogador',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_idioma',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.idioma'),
        ),
    ]
