# Generated by Django 5.0.4 on 2024-05-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_rename_tipo_genero_jogador_tp_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='_nm_senha',
            field=models.CharField(db_column='nm_senha', max_length=20, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='cd_cep',
            field=models.CharField(max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Alteração'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Exclusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Inlusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_nascimento',
            field=models.DateField(null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_escolaridade',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.escolaridade', verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_idioma',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.idioma', verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_jogador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_alteracao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário Alteração'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_exclusao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário Exclusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_inclusao',
            field=models.IntegerField(default=0, verbose_name='Usuário Inclusao'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nm_arquivo_imagem',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome Arquivo Imagem'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nm_avatar',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome Avatar'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nm_email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nm_jogador',
            field=models.CharField(max_length=80, verbose_name='Nome Jogador(a)'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='tp_genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não informado')], max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
