# Generated by Django 5.0.4 on 2024-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0003_alter_jogador__nm_senha_alter_jogador_cd_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaridade',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dt_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='id_usuario_alteracao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário alteração'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='id_usuario_exclusao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão'),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='id_usuario_inclusao',
            field=models.IntegerField(default=0, verbose_name='Usuário inclusao'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='ds_idioma',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição idioma'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='dt_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id_idioma',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID idioma'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id_usuario_alteracao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário alteração'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id_usuario_exclusao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='id_usuario_inclusao',
            field=models.IntegerField(default=0, verbose_name='Usuário inclusao'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nm_arquivo_estilo_css',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome arquivo estilo CSS'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nm_arquivo_imagem',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome arquivo imagem'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nm_idioma',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome idioma'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_alteracao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_exclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_jogador',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id jogador(a)'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_alteracao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário alteração'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_exclusao',
            field=models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id_usuario_inclusao',
            field=models.IntegerField(default=0, verbose_name='Usuário inclusao'),
        ),
    ]
